using UnityEngine;

public class ShadowSprite : MonoBehaviour
{
    public Transform player;

    private SpriteRenderer thisSprite;
    private SpriteRenderer playerSprite;

    private Color color;

    [Header("时间控制参数")]
    public float activeTime;    //显示时间
    [ReadOnly]
    public float activeStart;   //开始显示的时间点

    [Header("不透明度控制")]
    public float alphaOriginal; //透明度初始值
    public float alphaMultiplier;   //渐变乘积
    private float alpha;

    private void OnEnable()
    {
        player = GameObject.FindGameObjectWithTag("player").transform;
        thisSprite = GetComponent<SpriteRenderer>();
        playerSprite = player.GetComponent<SpriteRenderer>();

        alpha = alphaOriginal;

        thisSprite.sprite = playerSprite.sprite;

        transform.position = player.position;
        transform.localScale = player.localScale;
        transform.rotation = player.rotation;

        activeStart = Time.time;    //当前时间
    }

    void FixedUpdate()
    {
        alpha *= alphaMultiplier;

        color = new Color(0.5f, 0.5f, 1, alpha);  //蓝色

        thisSprite.color = color;

        //当时间超过显示时间
        if (Time.time >= activeStart + activeTime)
        {
            //返回对象池
            ShadowPool.instance.ReturnPool(this.gameObject);
        }
    }
}